### ISSUE TITLE
WFS Provider

### ISSUE THREAD

**Issue by asim27** [Mapsui/Mapsui#1918]
**Describe the bug**
I am not able to create a wfsprovider from latest version [4.0.0-beta.8](https://github.com/Mapsui/Mapsui/releases/tag/4.0.0-beta.8)
WfsProvider method with URI parameter raises System.NullReferenceException: 'Object reference not set to an instance of an object.'
on calling InitAsync() method
**To Reproduce**
1. Create a WFSProvidere with 
![image](https://user-images.githubusercontent.com/24899310/228777758-6096c088-4a9c-4546-80f8-fb3ce0156c6e.png)
2. Call .InitAsync() method on the WFSProvider instance.
3. Handle the exception
4. See the error

**Expected behavior**
System.NullReferenceException: 'Object reference not set to an instance of an object.'

**Screenshots**
![image](https://user-images.githubusercontent.com/24899310/228778308-13889023-fdd7-4fe1-b5b4-5eec3d758e22.png)

**Desktop (please complete the following information):**
 - Windows 11
 -  [4.0.0-beta.8](https://github.com/Mapsui/Mapsui/releases/tag/4.0.0-beta.8)

**Smartphone (please complete the following information):**
 - Windows Application

**Comment by inforithmics** [comment]
You should use WfsProvider.CreateAsync ... and WmsProvider.CreateAsync ... because Constructors cannot be asynchronous this methods initialize the wfs and wms provider asynchronous because a http call is involved.

**Comment by gpsaliola** [comment]
Ok, now i've tried this code:

```
        protected async override void OnAppearing()
        {
            base.OnAppearing();

            mapView.Map = await CreateMapAsync();

            Mapsui.Widgets.ScaleBar.ScaleBarWidget scale = new Mapsui.Widgets.ScaleBar.ScaleBarWidget(mapView.Map)
            {
                TextAlignment = Alignment.Center,
                HorizontalAlignment = HorizontalAlignment.Center,
                VerticalAlignment = VerticalAlignment.Top
            };
            mapView.Map.Widgets.Add(scale);
        }

        public static async Task<Mapsui.Map> CreateMapAsync()
        {
            var map = new Mapsui.Map { CRS = "EPSG:3857" };
            map.Layers.Add(await CreateLayerAsync());
            return map;
        }

        public static async Task<ILayer> CreateLayerAsync()
        {
            return new ImageLayer("mainmap") { DataSource = await CreateWmsProviderAsync() };
        }

        private static async Task<WmsProvider> CreateWmsProviderAsync()
        {
            const string wmsUrl = "http://sgi2.isprambiente.it/arcgis/services/raster/igm25k_lazio_wgs/ImageServer/WMSServer?service=wms&request=getCapabilities&version=1.3.0";
            var provider = await WmsProvider.CreateAsync(wmsUrl, persistentCache: null);
            provider.ContinueOnError = true;
            provider.TimeOut = 20000;
            provider.CRS = "EPSG:3857";
            provider.AddLayer("igm25k_lazio_wgs");
            provider.SetImageFormat((provider.OutputFormats)[0]);
            return provider;
        }

```
I obtain the following error:
System.ApplicationException: 'Could not download capabilities'

**Comment by inforithmics** [comment]
I would try https instead of http.

**Comment by gpsaliola** [comment]
I corrected the above code and tried again but nothing changes.
It should be noted that if I launch the link in the browser the capabilities xml file is loaded correctly.

**Comment by inforithmics** [comment]
I fixed here a WMSProvider Bug too.
https://github.com/Mapsui/Mapsui/pull/2007

The wms Http request was missing service=wms // newer wms service complain about it. older seem to not care.

**Comment by inforithmics** [comment]
this line sets the image format to
`provider.SetImageFormat((provider.OutputFormats)[0]);`

I think this is a missing case that needs to be handled in BitmapHelper.LoadBitmap

`image/tiff`

**Comment by pauldendulk** [comment]
> Because without the Style = RasterStyle() mapsui does not know how to render the imagelayer

This has caused confusion before. We need to improve it. The behavior needs to be consistent for all styles though.

**Comment by inforithmics** [comment]
I would suggest that The ImageLayer has RasterStyle set as default. So it would work out of the box. But still be customizable.

**Comment by gpsaliola** [comment]
I've tried the code suggested by [inforithmics](https://github.com/inforithmics) without success:

`

        protected async override void OnAppearing()
        {
            base.OnAppearing();

            mapView.Map = await CreateMapAsync();
        }

        public async Task<Map> CreateMapAsync()
        {
            var map = new Map {
                CRS = "EPSG:3857"
            };

            Mapsui.Widgets.ScaleBar.ScaleBarWidget scale = new Mapsui.Widgets.ScaleBar.ScaleBarWidget(mapView.Map)
            {
                TextAlignment = Alignment.Center,
                HorizontalAlignment = HorizontalAlignment.Center,
                VerticalAlignment = VerticalAlignment.Top
            };
            map.Widgets.Add(scale);

            map.Layers.Add(await CreateLayerAsync());
            return map;
        }

        public static async Task<ILayer> CreateLayerAsync()
        {
            return new ImageLayer("mainmap")
            {
                DataSource = await CreateWmsProviderAsync(),
                Style = new RasterStyle()
            };
        }

        private static async Task<WmsProvider> CreateWmsProviderAsync()
        {
            const string wmsUrl = "https://sgi2.isprambiente.it/arcgis/services/raster/igm25k_lazio_wgs/ImageServer/WMSServer?service=wms&request=getCapabilities&version=1.3.0";
            var provider = await WmsProvider.CreateAsync(wmsUrl, persistentCache: null);
            provider.ContinueOnError = true;
            provider.TimeOut = 20000;
            provider.CRS = "EPSG:3857";
            provider.AddLayer("igm25k_lazio_wgs");
            provider.SetImageFormat((provider.OutputFormats)[1]);
            return provider;
        }
`

Note that EPSG:3857 is not contained in the xml capabilities.
There are only: CRS:84, EPSG:4326, EPSG:0 (what does it mean?).
May be this the problem?
Thank you.

**Comment by inforithmics** [comment]
You should use EPSG:4326 and use a projection provider

**Comment by inforithmics** [comment]
Mapsui Projection.

https://mapsui.com/documentation/projections.html

**Comment by inforithmics** [comment]
There is something special about this wms service. Because in the sample I created here it still does not get the right data. My guess it fetches the wrong coordinates. But still investigating.

https://github.com/Mapsui/Mapsui/pull/2008

**Comment by gpsaliola** [comment]
Thank you for info.
I've made another test with this server (Spain orthophoto): 
https://www.ign.es/wms-inspire/pnoa-ma?service=wms&request=getCapabilities
the layer is:
OI.OrthoimageCoverage

Test 1: map CRS: EPSG:3857, CRS provider: EPSG:3857 => it works fine
Test 2: map CRS: EPSG:3857, CRS provider: EPSG:4326 => map is shown but scale is wrong and perhaps coordinates
Test 3: map CRS: EPSG:4326, CRS provider: EPSG:4326 => as above

May be test 2 needs implementing Mapsui projection as [inforithmics](https://github.com/inforithmics) said.
Why test 3 doesn't work?
Thank you.

**Comment by inforithmics** [comment]
The wms server you are using is an Archivs server. Maybe you can use mapsui.Archie's to fetch the data.

**Comment by gpsaliola** [comment]
Sorry but I'm a bit confused.
Where do you know that the server is Archivs (or Archie)?
I've never heard of it before.
In other environments (eg: OpenLayers) it is a WMS server like any other.

**Comment by inforithmics** [comment]
Auto correction error I meant ArcGis

**Comment by gpsaliola** [comment]
How do you know it's an ArcGIS server?
Is there any documentation or examples on Masui.ArcGIS?

**Comment by inforithmics** [comment]
It's only a guess because it has arcgis in it's url.

**Comment by gpsaliola** [comment]
Thank you. I'll try it.
However it responds with a classic XSD WMS version 1.3.0.
In OpenLayers the provider used for both my examples is the same (ol.source.TileWMS).

**Comment by pauldendulk** [comment]
The ArcGIS WMS is supposed to follow the OGC standard. It can always be a bit different but I would expect the implementation is correct. It probably works correctly in a QGIS client as well.

**Comment by inforithmics** [comment]
It is the crs: with EPSG:4326 the axis are changed.
see:
https://github.com/Mapsui/Mapsui/issues/1925#issuecomment-1493411132

**Comment by gpsaliola** [comment]
The "DPI", "MAP_RESOLUTION" and "FORMAT_OPTIONS" parameters are not actually needed.
So both link are identical except the order of the coordinates.
I know post #1925, I reported this issue but I thought the release candidate version fixed it.
I've tried the following code:

`

        protected async override void OnAppearing()
        {
            base.OnAppearing();

            mapView.Map = await CreateMapAsync();
        }

        public async Task<Map> CreateMapAsync()
        {
            var map = new Map {
                CRS = "EPSG:3857"
            };

            Mapsui.Widgets.ScaleBar.ScaleBarWidget scale = new Mapsui.Widgets.ScaleBar.ScaleBarWidget(mapView.Map)
            {
                TextAlignment = Alignment.Center,
                HorizontalAlignment = HorizontalAlignment.Center,
                VerticalAlignment = VerticalAlignment.Top
            };
            map.Widgets.Add(scale);

            map.Layers.Add(await CreateLayerAsync());
            return map;
        }

        public static async Task<ILayer> CreateLayerAsync()
        {
            return new ImageLayer("mainmap")
            {
                DataSource = await CreateWmsProviderAsync(),
                Style = new RasterStyle(), 
                Attribution = new Hyperlink() { 
                    Text = "attributions"
                } 
            };
        }

        private static async Task<WmsProvider> CreateWmsProviderAsync()
        {
            const string wmsUrl = "https://sgi2.isprambiente.it/arcgis/services/raster/igm25k_lazio_wgs/ImageServer/WMSServer?service=wms&request=getCapabilities&version=1.3.0";
            var provider = await WmsProvider.CreateAsync(wmsUrl, persistentCache: null);
            provider.ContinueOnError = true;
            provider.TimeOut = 20000;
            provider.CRS = "CRS:84";
            provider.AddLayer("igm25k_lazio_wgs");
            provider.SetImageFormat((provider.OutputFormats)[1]);
            return provider;
        }
    }
`
The map is shown but there is an error on scale and coordinates. Zoom flickers.

**Comment by gpsaliola** [comment]
I've tried this server also but the map isn't shown:
https://geoportale.regione.lazio.it/geoserver/ows?service=wms&request=getCapabilities&version=1.3.0
layer: "geonode:ctr_5k_retiled"
However, it should be considered that not all services have CRS:84.

**Comment by inforithmics** [comment]
I saw that there is a ProjectionProvider missing in Mapsui I'll add it to in the pull request.

**Comment by inforithmics** [comment]
After the pull request with the fixes goes on this sample should work now.

```
﻿using Mapsui.Cache;
using Mapsui.Layers;
using Mapsui.Providers.Wms;
using System.Threading.Tasks;
using Mapsui.Nts.Extensions;
using Mapsui.Providers;
using Mapsui.Styles;
using NetTopologySuite.Geometries;

namespace Mapsui.Samples.Common.Maps.DataFormats;

public class WmsProjectionSample : ISample
{
    public string Name => " 6 WMS Projection";
    public string Category => "Data Formats";
    public static IUrlPersistentCache? DefaultCache { get; set; }

    public async Task<Map> CreateMapAsync()
    {
        var map = new Mapsui.Map
        {
            CRS = "EPSG:3857",
        };

        // The WMS request needs a CRS
        map.Layers.Add(await CreateLayerAsync());
        return map;
    }

    public static async Task<ILayer> CreateLayerAsync()
    {
        var dataSource = new ProjectingProvider(await CreateWmsProviderAsync())
        {
            CRS = "EPSG:3857"
        };

        return new ImageLayer("mainmap")
        {
            DataSource = dataSource,
            Style = new RasterStyle()
        };
    }

    private static async Task<WmsProvider> CreateWmsProviderAsync()
    {
        const string wmsUrl = "https://sgi2.isprambiente.it/arcgis/services/raster/igm25k_lazio_wgs/ImageServer/WMSServer?service=wms&request=getCapabilities&version=1.3.0";
        var provider = await WmsProvider.CreateAsync(wmsUrl, persistentCache: DefaultCache);
        provider.ContinueOnError = true;
        provider.TimeOut = 20000;
        provider.CRS = "EPSG:4326";
        provider.AddLayer("igm25k_lazio_wgs");
        provider.SetImageFormat((provider.OutputFormats)[1]);
        return provider;
    }
}
```

**Comment by gpsaliola** [comment]
I've tried this code:

`

	using System.Threading.Tasks;
	using Xamarin.Forms;
	using Mapsui;
	using Mapsui.Layers;
	using Mapsui.Providers.Wms;
	using Mapsui.Extensions;
	using Mapsui.Widgets;
	using Mapsui.Styles;
	using Mapsui.Cache;
	using System.ComponentModel;
	using Mapsui.Projections;
	using System.Collections.Generic;
	
	namespace OkMap.Views
	{
		public partial class Maps : ContentPage
		{
			public static IUrlPersistentCache DefaultCache { get; set; }
	
			public  Maps()
			{
				InitializeComponent();
			}
	
			protected async override void OnAppearing()
			{
				base.OnAppearing();
	
				mapView.Map = await CreateMapAsync();
				mapView.Map.Navigator.ViewportChanged += mapView_ViewPortChanged;
			}
	
			public async Task<Map> CreateMapAsync()
			{
				var map = new Map {
					CRS = "EPSG:3857"
				};
	
				Mapsui.Widgets.ScaleBar.ScaleBarWidget scale = new Mapsui.Widgets.ScaleBar.ScaleBarWidget(mapView.Map)
				{
					TextAlignment = Alignment.Center,
					HorizontalAlignment = HorizontalAlignment.Center,
					VerticalAlignment = VerticalAlignment.Top
				};
				map.Widgets.Add(scale);
	
				map.Layers.Add(await CreateLayerAsync());
				return map;
			}
	
			public static async Task<ILayer> CreateLayerAsync()
			{
				return new ImageLayer("mainmap")
				{
					DataSource = await CreateWmsProviderAsync(),
					Style = new RasterStyle(), 
					Attribution = new Hyperlink() { 
						Text = "attributions"
					} 
				};
			}
	
			private static async Task<WmsProvider> CreateWmsProviderAsync()
			{
				const string wmsUrl = "https://sgi2.isprambiente.it/arcgis/services/raster/igm25k_lazio_wgs/ImageServer/WMSServer?service=wms&request=getCapabilities&version=1.3.0";
				//const string wmsUrl = "https://geoportale.regione.lazio.it/geoserver/ows?service=wms&request=getCapabilities&version=1.3.0";
				//const string wmsUrl = "https://www.ign.es/wms-inspire/pnoa-ma?service=wms&request=getCapabilities";
				
				var provider = await WmsProvider.CreateAsync(wmsUrl, persistentCache: DefaultCache);
				provider.ContinueOnError = true;
				provider.TimeOut = 20000;
				provider.CRS = "EPSG:4326";
	
				provider.AddLayer("igm25k_lazio_wgs");
				//provider.AddLayer("geonode:ctr_5k_retiled");
				//provider.AddLayer("OI.OrthoimageCoverage");
				
				provider.SetImageFormat((provider.OutputFormats)[1]);
				return provider;
			}
	
			private void mapView_ViewPortChanged(object sender, PropertyChangedEventArgs propertyChangedEventArgs)
			{
				(double lon, double lat) mapCenter = SphericalMercator.ToLonLat(mapView.Map.Navigator.Viewport.CenterX, mapView.Map.Navigator.Viewport.CenterY);
	
				Device.BeginInvokeOnMainThread(() => {
					lblCoordinates.Text = mapView.Map.Navigator.Viewport.CenterY.ToString() + " " + mapView.Map.Navigator.Viewport.CenterX.ToString() + " " + GetZoom().ToString();
				});
			}
	
			private int GetZoom()
			{
				IReadOnlyList<double> resolutions = mapView.Map.Navigator.Resolutions;
				for (int i = 0; i <= resolutions.Count - 1; i++)
				{
					if (mapView.Map.Navigator.Viewport.Resolution >= resolutions[i])
						return i + 1;
				}
				return resolutions.Count;
			}
		}
	}
`

1- Shown scale is wrong
2- Map in streched horizzontally (grid is formed by rectangle and not by square)
3- This statement mapView.Map.Navigator.Resolutions return zero length array
I downloaded the latest version 4.0.0-rc.2.
What am I doing wrong?
Thank you.

**Comment by charlenni** [comment]
I'm not followed the whole discussion, so I might be wrong.

If you read [this](https://gis.stackexchange.com/questions/48949/epsg-3857-or-4326-for-web-mapping) info, and compare it with your last code, then I fear, that you try to fit EPSG:4326 tiles in a EPSG:3857 map, which, with my understanding, doesn't work.

**Comment by gpsaliola** [comment]
I know the difference between datum and projection and between EPSG.4326 and EPSG:3857.
Based on Mapsui official documentation (see below), I thought Mapsui was able to convert between these two systems.
However even if I crete the map with EPSG:4326 CRS the problem remains the same.

## Supported coordinate systems (CRSes)

Out of the box Mapsui only supports the projection between two coordinate systems.
- [EPSG:4326](https://epsg.io/4326) or lat/lon, or WGS84. GPS coordinates are in lat/lon
- [EPSG:3857](https://epsg.io/3857) or SphericalMercator, or WebMercator, PseudoMercator. This is the coordinate system used in the maps of google and openstreetmap.

**Comment by charlenni** [comment]
Yes, Mapsui knows both, but I could not find any conversion from one format to another. What you could do is convert coordinates from one of these projections to Mapsui and vice versa. But there isn't a conversion of raster data.

**Comment by gpsaliola** [comment]
However even if the CRS of the map and the CRS of the provider are the same, there are problems about map scale and map resolutions.

**Comment by inforithmics** [comment]
My fixes are not yet in 4.0.0-rc.2. so they should be in the next rc or release.  The Resolutions property I have to investigate why this is 0 length.

**Comment by gpsaliola** [comment]
I've made new tests with 4.0.0-rc.3 version.
The issue doesn't seem solved (no map was shown).
I've tryed these servers with EPSG:3857:

https://www.ign.es/wms-inspire/pnoa-ma?service=wms&request=getCapabilities
layer: OI.OrthoimageCoverage

https://wms.geo.admin.ch?service=wms&request=getCapabilities
layer: ch.swisstopo.pixelkarte-farbe

I also tried these servers with EPSG:4326:

https://sgi2.isprambiente.it/arcgis/services/raster/igm25k_lazio_wgs/ImageServer/WMSServer?service=wms&request=getCapabilities
layer: igm25k_lazio_wgs

https://geoportale.regione.lazio.it/geoserver/ows?service=wms&request=getCapabilities
layer: geonode:ctr_5k_retiled

The first seems works but:
1. Scale is wrong
2. Map is streched horizontally
3. Coordinates seems wrong
4. The zoom level cannot be determined

Is it possible to manage at least these CRS? (the most important)
EPSG:3857, EPSG:4326, CRS:84

**Comment by inforithmics** [comment]
```
 public async Task<Map> CreateMapAsync()
    {
        var map = new Mapsui.Map
        {
            CRS = "EPSG:3857",
        };

        // The WMS request needs a CRS
        map.Layers.Add(await CreateLayerAsync());
        return map;
    }

    public static async Task<ILayer> CreateLayerAsync()
    {
        var dataSource = new ProjectingProvider(await CreateWmsProviderAsync())
        {
            CRS = "EPSG:3857"
        };

        return new ImageLayer("mainmap")
        {
            DataSource = dataSource,
            Style = new RasterStyle()
        };
    }

    private static async Task<WmsProvider> CreateWmsProviderAsync()
    {
        const string wmsUrl = "https://sgi2.isprambiente.it/arcgis/services/raster/igm25k_lazio_wgs/ImageServer/WMSServer?service=wms&request=getCapabilities&version=1.3.0";
        var provider = await WmsProvider.CreateAsync(wmsUrl, persistentCache: DefaultCache);
        provider.ContinueOnError = true;
        provider.TimeOut = 20000;
        provider.CRS = "EPSG:4326";
        provider.AddLayer("igm25k_lazio_wgs");
        provider.SetImageFormat((provider.OutputFormats)[1]);
        return provider;
    }
```

This Code works (is the sample that the map displays). A Projection Provider needs to be used so that the WmsCalls are projected from EPSG:4326 to EPSG:3857 and the projection needs to be set on the map

**Comment by inforithmics** [comment]
1. Could be a Bug
2. Needs Mapsui.Extensions and the DotSpatial Projections. (Should know EPSG:6706) (Projection / Shapefile with Projection)
3. Does not work because this is not a Tiled Wms Layer, You have to convert the WMS To Tiled. (Data Formats/ 4 WMS called tiled)

**Comment by gpsaliola** [comment]
Thank you very much.
Is it possible to speculate when the release 4 will be released?

**Comment by inforithmics** [comment]
I think this will take some time but with this link a mapsui version with the fixes can be downloaded and then with a local nuget package folder used.

```
<configuration>
  <config>
    <add key="globalPackagesFolder" value="C:\path\to\custom\folder" />
  </config>
</configuration>

```

https://github.com/Mapsui/Mapsui/suites/13681044682/artifacts/756030684

**Comment by gpsaliola** [comment]
Many thanks!

**Comment by gpsaliola** [comment]
Two question. 
1. These files https://github.com/Mapsui/Mapsui/suites/13681044682/artifacts/756030684 are evergreen or where it's possible to download the latest versions?
2. Which is the file where i should put these tags?
```
<configuration>
  <config>
    <add key="local" value="C:\path\to\custom\folder" />
  </config>
</configuration>
```
Thank you!

**Comment by inforithmics** [comment]
you can add a nuget.config file.

with following content.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="local-packages" value="path/to/your/local/package/folder" />
  </packageSources>
</configuration>
```

**Comment by gpsaliola** [comment]
Ok, thank you!

**Comment by pauldendulk** [comment]
Answered and fixed with https://github.com/Mapsui/Mapsui/pull/2073

**Comment by pauldendulk** [comment]
ah great you resolved it. And yes, I am a big fan of explicit errors, so this could definitely be improved. 

I am also considering rewriting WFS entirely. Perhaps when using AI and providing good tests as benchmarks this may not be that hard.
