### ISSUE TITLE
[Android] Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by MaticDiba** [Mapsui/Mapsui#477]
Hi,
I'm using Mapsui with Xamarin.Forms. When I'm dragging and zooming in/out the map, I often get this exception. And I'm not sure where to catch it. 

Mapsui version is 1.4.2

This is StackTrace I get:

```
07-22 14:33:27.716 I/MonoDroid(11986): System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
07-22 14:33:27.716 I/MonoDroid(11986):   at System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) [0x0000b] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
07-22 14:33:27.716 I/MonoDroid(11986):   at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () [0x00013] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
07-22 14:33:27.716 I/MonoDroid(11986):   at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x0004a] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
07-22 14:33:27.716 I/MonoDroid(11986):   at Mapsui.Map.get_Envelope () [0x0003e] in <bd6c770b2d1b4c27bce3851e2242b36f>:0 
07-22 14:33:27.716 I/MonoDroid(11986):   at Mapsui.UI.Android.MapControl.MapView_Touch (System.Object sender, Android.Views.View+TouchEventArgs args) [0x0021b] in <c13b5b47cf5c441089ad69c9299ca90f>:0 
07-22 14:33:27.716 I/MonoDroid(11986):   at Android.Views.View+IOnTouchListenerImplementor.OnTouch (Android.Views.View v, Android.Views.MotionEvent e) [0x00014] in <263adecfa58f4c449f1ff56156d886fd>:0 
07-22 14:33:27.716 I/MonoDroid(11986):   at Android.Views.View+IOnTouchListenerInvoker.n_OnTouch_Landroid_view_View_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_v, System.IntPtr native_e) [0x00017] in <263adecfa58f4c449f1ff56156d886fd>:0 
07-22 14:33:27.716 I/MonoDroid(11986):   at (wrapper dynamic-method) System.Object.b879ca1a-12ab-4dd9-b8d8-e8a7923d0c07(intptr,intptr,intptr,intptr)
```

**Comment by pauldendulk** [comment]
What kind of layers do you use?

**Comment by MaticDiba** [comment]
For map layer I'm using OpenStreetMap layer from Mapsui.Utilities.

Besides that I also use layer with points I add to the map and it's infolayer. There are more then 10k points total. I show them only after specific Resolution. If resolution is lower than the one specified, I remove that layer. 

I've also added a lock before the code where I add and remove the layer.

**Comment by MaticDiba** [comment]
I closed it by accident. Sorry for that.

**Comment by pauldendulk** [comment]
What kind of layer do you use as point layer?

**Comment by MaticDiba** [comment]
I create Features to which I add Feature with Geometry as a point, with  Lebel and some extra parameters added as KeyValues. Then I add Features to the Layer as a DataSource with MemoryProvider. I also add specific Style to the Layer. I add this layer to Layers property of my map and InfoLayer property.

**Comment by pauldendulk** [comment]
So you type of layer is a regular 'Layer'. What type is your DataSource?

**Comment by MaticDiba** [comment]
That is correct. DataSource is of type MemoryProvider, which is constructed with type Feature.

**Comment by pauldendulk** [comment]
I know there is an issue the with MemoryProvider.Clear. Do you call it explicitly at some point? 

> If resolution is lower than the one specified, I remove that layer.
How do you remove it?

**Comment by MaticDiba** [comment]
No. 

I tried to reproduce the issue. The way I did it was swiping around like crazy, zooming in and out. Also zooming over the threshold where I remove the layer. And then zoomin againg, to display it again. And at some point it crashes with the same exception. Do you have any suggestion how I could catch that?

**Comment by pauldendulk** [comment]
How do you remove the layer?

**Comment by MaticDiba** [comment]
Here is the snippet
`
var locationLayer = mapControl.NativeMap.Layers.FirstOrDefault(l => l.Name == "MyLayerName");
                if (locationLayer != null)
                {
                    if (locationLayer != null)
                        mapControl.NativeMap.Layers.Remove(locationLayer);
                    mapControl.NativeMap.ViewChanged(true);
                }
`

**Comment by pauldendulk** [comment]
There should be catch in the OnTouch of the Android MapControl to catch this. I don't think that you can catch it. 

Can you reproduce the problem if you do not remove the layer?

**Comment by MaticDiba** [comment]
No, I haven't been able to reproduce that. I am quite sure that the problem is there. That's why I added lock around add and remove statements. So they can't be triggered one over another.

**Comment by MaticDiba** [comment]
I tried that. It gets stuck at:

```c#
mapControl.NativeMap.ViewChanged(true);
```
which I call right after 
```c# 
layer.Enabled = false; 
```
This was also a reason I started working with add remove.

**Comment by pauldendulk** [comment]
@MaticDiba btw, You can use the MemoryProvider2 without upgrading to 1.4.5. You can just copy the file to your project.

https://raw.githubusercontent.com/Mapsui/Mapsui/1.4/Mapsui/Providers/MemoryProvider2.cs

**Comment by pauldendulk** [comment]
@MaticDiba In 1.4.7 you can just use MemoryProvider, without the 2.

**Comment by pauldendulk** [comment]
@MaticDiba Very interested to see if this fixes your problem.

**Comment by MaticDiba** [comment]
Hi Paul,
sorry for my late replay. I'm away until 5th of August. I will test it when I come back.

**Comment by pauldendulk** [comment]
@MaticDiba Is this fixed now?

**Comment by MaticDiba** [comment]
Hi, Paul. Yes, this worked. Sorry for late replay.

**Comment by pauldendulk** [comment]
@MaticDiba Thanks for wrapping this up. These kind of errors are high priority.

**Comment by helderdb** [comment]
Still having this issue in 1.4.8

Changed to MemoryProvider2 and not having the issue since. Although it is deprecated.

**Comment by pauldendulk** [comment]
oh, this is bad news.

The

**Comment by pauldendulk** [comment]
Oh, this is bad news.

The MemoryProvider2 is identical in logic to MemoryProvider. Within MemoryProvider there is no mutation of the features at all. The only scenario I see is that a feature collection is added to the MemoryProvider (in the constructor or through ReplaceFeatures) and that from the outside there is still a pointer to that list which mutates it.

More likely is perhaps old versions of dlls that are not rebuilt. I have seen this a lot in Xamarin. To resolve this delete your bin and obj folders.

Are you sure the collection was modified is in the MemoryProvider? Do you have a stacktrace for me?

**Comment by pauldendulk** [comment]
Also, what do you do in the UI when this happens? Are you editing?

**Comment by helderdb** [comment]
I'm only adding multiple features on the map...

**Comment by pauldendulk** [comment]
Could you post a stacktrace?

**Comment by pauldendulk** [comment]
@helderdb I will have some time today to look at this.

**Comment by helderdb** [comment]
@pauldendulk No... That's the reason why I'm currently using MemoryProvider2.
I encounter it with MemoryProvider about 1/7 times. I haven't encountered it with MemoryProvider2

**Comment by pauldendulk** [comment]
oh, and another question. What kind of layers do you have in your application. You are adding features using the MemoryProvider? WritableLayer is a more logical choice but it has no dependency on MemoryProvider.

**Comment by pauldendulk** [comment]
And do all your projects reference Mapsui 1.4.8?

**Comment by pauldendulk** [comment]
@helderdb Can you still reproduce the issue if you clear all bin and obj folders and make sure all projects reference 1.4.8?

**Comment by helderdb** [comment]
I did that many many times but it did not fix it. All of them reference 1.4.8 yes.

**Comment by pauldendulk** [comment]
What type of layer do you use to add the polygons to?

**Comment by pauldendulk** [comment]
I closing this until there is a way to reproduce this.
