### ISSUE TITLE
[Forms.iOS] Zoom-Lock when using the Home function

### ISSUE THREAD

**Issue by Sebastian1989101** [Mapsui/Mapsui#596]
When using the home button while a single finger for panning is still on the screen, and then go back to the app the map is only able to zoom from now on (two fingure gesture). This is espacially a problem on the iPhone X because you leave the app with a touch gesture so the finger is on the screen while the app is minimizing. 

Did not verified it with the Mapsui Examples yet but I wanted to report it before I forget it.

**Comment by pauldendulk** [comment]
Thanks for reporting this. I reproduce something weird. After pressing home and returning to the app it seems there is still a 'ghost' finger holding the map. Touching with one finger induces a pinch gesture. 

It guess this is what you mean but it was not fully clear when reading it initially.

**Comment by charlenni** [comment]
I know, what the problem is, but haven't the time to correct it. Give me some time.

@Sebastian1989101 It would be nice, if you could add the platform in the form of Forms.iOS. With this, we know, that it is a Forms MapControl problem and not a iOS and Forms MapControl problem.

**Comment by pauldendulk** [comment]
ah okay. 

One more thing. I can not reproduce it in the native iOS sample, only in forms.

**Comment by Sebastian1989101** [comment]
@pauldendulk Thats exactly what I mean. Sorry for the hard-to-read text, I'm not very good when it comes to write english. And yes, it seems to be exclusive to Forms.iOS, as mentioned I was not entirely sure because I was on the road and just wanted to report it before I forget it.

@charlenni Changed the title. And good to know that it is at least a "known" problem. :)

**Comment by charlenni** [comment]
@Sebastian1989101 Äh, it wasn't a known problem. But when you report the issue, I know immediatly know, what the problem is :)

**Comment by Sebastian1989101** [comment]
@charlenni That's why I added the "" around the known. ;)

**Comment by charlenni** [comment]
I have an array, where the fingers for the OnTouch event are stored. The problem is, that I only have one event to clear this: OnUnfocused. Try to clear the fingers array in this event. Should solve the problem, but I should test it.

**Comment by pauldendulk** [comment]
I merged the PR and hope to release a new beta tonight.

**Comment by Sebastian1989101** [comment]
@charlenni Did the `SizeChanged` event gets called on your fix? Because when I test it with the `SizeChanged` event registered, it is not called when the app gets minimized and resumed. 

Also this problem might be a reverse problem too. If I start zooming with the pinch gesture (two fingers) it removes both fingers from the array when I lift only one up to scroll / pan (1 finger gesture) around. Is this as intended? Because it was allowed on Mapsui 1.x to immediatly use the pan gesture when only 1 finger was lifted from the pinch gesture.

**Comment by pauldendulk** [comment]
Please test with beta 17

**Comment by Sebastian1989101** [comment]
@pauldendulk @charlenni as expected the issue still exists (with beta 17) in both "directions". 

1. Leaving (Home-Button) the app while a finger is still on the map and then returning to the app results in a pinch gesture (2 fingers) instead of a pan gesture (1 finger). 

2. Using the pinch gesture (2 fingers) to zoom and lift only one finger from the map to switch to a pan gesture (1 finger) results in no reaction at all until I put my finger up and down again.

**Comment by charlenni** [comment]
For your information: the handling of gestures are complete new. There is no native handling. So it could be, that I have “implemented” some “special features” 😉

I try to correct them as I get knowledge of them. So I beg your pardon in advance.

**Comment by Sebastian1989101** [comment]
@charlenni Oh I didn't know that there is a complete new implementation for handling. That might explain the differences. Should I still report any difference to Mapsui 1.x I notice for the gesture handling? As so far, the two above are the only I noticed so far.

**Comment by charlenni** [comment]
@Sebastian1989101 That would be great. I try to make the handling of Mapsui 2.0 Forms the same as Mapsui 1.0 on the different platforms.

**Comment by Sebastian1989101** [comment]
@charlenni When opening the master menu (on a master detail app) while one finger on the map the same problem happen with the zoom lock as it does when you minimize the app while doing so. Has the map some kind of unfocus event for such cases? Or would it be possible to have a method to call to clear the inputs (because my app knows when it will be go to sleep and when the master menu opens for example). 

Also the map acts kinda strange when you put more than 2 fingers on it at a time.

**Comment by charlenni** [comment]
So now I looked into the OnTouch event of SkiaSharp and found the problem.

SkiaSharps OnTouch event has the following action types:
- Pressed (already handled)
- Released (already handled)
- Move (already handled)
- Cancelled
- Exited
- Entered
As you can see, I didn't handled the last three. I don't think, that we should use Exited and Entered. They occure, if you leave the map with finger on screen to another view or to an edge. But Cancelled should be handled, because it is this event, that occures, if you lift your finger outside of the view.

**Comment by pauldendulk** [comment]
2.0.0-beta.18 has some more fixes for this.

**Comment by Sebastian1989101** [comment]
First results after debugging (Android): 

- Zooming (pinch gesture) is no longer possible, when one finger is not on a tile from the tilelayer, in the simulator with beta 18. The map won't react to the input and instead pan around. At least it works on a real device. 

- SingleTap-, DoubleTap- and LongTap-Events are no longer fired on a real device (tested with 3 different devices, Samsung Galaxy S8, ASUS ROG Phone and Huawei Mate X). These events works in the simulator on the other hand.. 

I guess there is something wrong with the events and that the event that is not triggered on the simlator to pinch outside of the tiles is the one blocking the tap events on the real device. I will test iOS next and as long as it does not have the same bugs (because without the tap event fired properly, the users can't test a huge part of the app) I will push it to the TF users later today.

**Comment by pauldendulk** [comment]
Thanks for testing and the clear report.

**Comment by Sebastian1989101** [comment]
@pauldendulk Just extended the testing with a 2nd person from the team and it seems like at least the previous beta (17) has the same problem on samsung galaxy devices that the three tap events not trigger as they should. 

The pinch gesture on the other hand works since I rebuild the app.. maybe some kind of compilation error?

**Comment by Sebastian1989101** [comment]
@pauldendulk Based on the feedback I got so far from the iOS TestFlight users, the initial reported issue seems to be solved.

**Comment by pauldendulk** [comment]
@Sebastian1989101 Thanks a lot!
